[package]
name = "p2p-strategy-core"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
p2p-primitives-math.workspace = true
p2p-primitives-types.workspace = true
commonware-codec.workspace = true
commonware-math.workspace = true
rand.workspace = true
tracing.workspace = true
